### Create Login ###
POST http://localhost:8080/users
Content-Type: application/json

{
  "username": "emanuel",
  "password": "123"
}

### Login ###
POST http://localhost:8080/login
Content-Type: application/json

{
  "username": "admin",
  "password": "123"
}

### Create Tweet ###
POST http://localhost:8080/tweets
Content-Type: application/json

{
  "content": "emanuel tweet"
}

### Public feed ###
GET http://localhost:8080/public-feed

### Delete Tweet ###
DELETE http://localhost:8080/tweets/53

### Get Users ###
GET http://localhost:8080/users
Authorization: Bearer eyJhbGciOiJSUzI1NiJ9.eyJpc3MiOiJteWJhY2tlbmQiLCJzdWIiOiI1Yzg1Y2VhMi03MzM3LTQ2NjAtYWQ5Yi1jODEzZjljOTllMjEiLCJleHAiOjE3NDg4NzU1NDYsImlhdCI6MTc0ODg3NTI0Niwic2NvcGUiOiJhZG1pbiJ9.Br2ZoWGC7Hz7ZrTy0MrMx4ZXJnFnk4rBN2ccJdlLud4hTySIaubGfFcHc7JC9HITnE4icGYSueo0Il9epGc6y-iWWsOrjs-zSDRXplASMFv2YEte9byTIrsFLwffgbc5kx5OKCHfiNU6UHsgDYWaVx3YgGz2BHJFzYzwSAKTGoQhsKcYblEMWYl8kMpv0xx-JksuBb4Mb6zTunBC5xJSsvtsGuHw75IZPi6-u0kgKqD9AmCzosFhn3JTRcuHx-pdOLwni_uakaL9poZ9-gjAqnJwUM3zvS7684CNwCUvYs8I1WCVcKDi2-TNINiS0Cpz2-1SRVDfKmNU3fOuiKsk8Q
